services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: >
      sh -c "
      pytest -sv --alluredir=allure-results &&
      allure generate allure-results --clean -o allure-report
      "
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}