name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        run: docker compose up --exit-code-from regression

      - name: Prepare Allure results
        run: |
          mkdir -p ./allure-results/history
          if [ -d "gh-pages/history" ]; then
            cp -r gh-pages/history/* ./allure-results/history/
          fi

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: ./allure-results
          allure_report: ./allure-report
          keep_history: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report