name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker compose build

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker compose run --rm regression pytest --alluredir=allure-results || true

      - name: Prepare Allure results directory
        run: |
          mkdir -p allure-results/history
          if [ -d "gh-pages/history" ]; then
            cp -r gh-pages/history/* allure-results/history/
          fi

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_history: true

      - name: Update Allure history
        run: |
          mkdir -p gh-pages/history
          cp -r allure-report/history/* gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: ./
          keep_files: false