name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout gh-pages for Allure history
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set up Docker Compose
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Build Docker images
        run: docker compose build

      - name: Run UI-tests and generate report
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker compose up --exit-code-from regression || true
          # Отчёт теперь генерируется автоматически в контейнере

      - name: Copy history from gh-pages
        run: |
          mkdir -p ./allure-results/history
          if [ -d "gh-pages/history" ]; then
            cp -R gh-pages/history/* ./allure-results/history/
          fi

      - name: Update Allure history
        run: |
          mkdir -p gh-pages/history
          if [ -d "allure-report/history" ]; then
            cp -R allure-report/history/* gh-pages/history/
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true