name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Run UI tests
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker-compose up --exit-code-from regression --build || true

      - name: Prepare test results
        run: |
          mkdir -p allure-results/history
          # Копируем историю только если она существует
          if [ -d "gh-pages/history" ]; then
            cp -R gh-pages/history/* allure-results/history/
          fi

      - name: Generate Allure report
        run: |
          # Проверяем наличие результатов тестов
          if [ -d "allure-results" ]; then
            docker compose run -e JAVA_HOME=/usr/lib/jvm/java-11-openjdk \
              regression /bin/sh -c "/usr/bin/allure generate /app/allure-results --clean -o /app/allure-report"
          else
            echo "Error: No test results found in allure-results directory!"
            exit 1
          fi

          # Проверяем что отчет сгенерировался
          if [ ! -d "allure-report" ]; then
            echo "Error: Allure report generation failed!"
            exit 1
          fi

      - name: Update history
        run: |
          mkdir -p gh-pages/history
          if [ -d "allure-report/history" ]; then
            cp -R allure-report/history/* gh-pages/history/
          else
            echo "Warning: No history found in allure report"
          fi

      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true