name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v2

      - name: Установить Docker Compose
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install docker-compose

      - name: Запуск UI-тестов через docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker compose up --exit-code-from regression
          docker compose down

      - name: Генерация отчёта Allure
        run: |
          docker compose run regression /bin/sh -c "allure generate /allure-results --clean -o /allure-report"

      - name: Публикация Allure отчёта на GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
